name: Test artifacts
on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with: {go-version: '1.14'}

      - run: go build

      - name: Debug
        run: |
          ls -alhF

      - uses: actions/upload-artifact@v2-preview
        with:
          name: foo
          path: actions-test

      - name: Debug
        run: |
          ls -alhF

      - uses: actions/download-artifact@v2
        with:
          name: foo
          path: foo

      - name: Debug
        run: |
          file foo
          ls -alhF foo
          file foo/actions-test
          chmod +x foo/actions-test
          ./foo/actions-test
