name: Test artifacts
on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with: {go-version: '1.14'}

      - run: |
          go build
          file actions-test
          ./actions-test

      - uses: actions/upload-artifact@v1
        with:
          name: hello-world
          path: actions-test

      - uses: actions/download-artifact@v1
        with:
          name: hello-world

      - name: Debug
        run: |
          ls -alhF
          ls -alhF hello-world/
          file hello-world/actions-test
          chmod +x hello-world/actions-test
          ./hello-world/actions-test

      # - name: Create a GitHub Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: foo
      #     release_name: foo

      # - name: Upload binary to GitHub Release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./foo/actions-test
      #     asset_name: actions-test
      #     asset_content_type: application/x-executable
