name: CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: debug
      run: |
        env
        echo "----"
        echo $HOME
        echo ~/cats

    - name: debug2
      run: |
        export C=~/foo
        printenv
